version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/code-deploy/shortly-backend
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh # Install dependencies
      runas: ubuntu
      timeout: 600
  Install:
    - location: scripts/install.sh # Install the application
      runas: ubuntu
      timeout: 600
  AfterInstall:
    - location: scripts/after_install.sh # Perform actions after installation
      runas: ubuntu
      timeout: 300
      # Configurações do SNS
      notification:
        topic: arn:aws:sns:us-east-1:802157251259:code-deploy-sns-topic
        subject: "Deployment completed successfully"
        status: "SUCCESS"
  ApplicationStart:
    - location: scripts/application_start.sh # Start the application
      runas: ubuntu
      timeout: 300
  ApplicationStop:
    - location: scripts/application_stop.sh # Stop the application
      runas: ubuntu
      timeout: 300