version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/code-deploy/prod-shortly
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/code-deploy/prod-shortly/scripts/aws
    pattern: "**"
    mode: 755
    type:
      - file
  - object: /home/ubuntu/code-deploy/prod-shortly/scripts/server
    pattern: "**"
    mode: 755
    type:
      - file
hooks:
  ApplicationStop:
    - location: scripts/aws/application_stop.sh # Stop the application
      runas: root
      timeout: 300
  BeforeInstall:
    - location: scripts/aws/before_install.sh # Install dependencies
      runas: root
      timeout: 600
  AfterInstall:
    - location: scripts/aws/after_install.sh # Perform actions after installation
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/aws/application_start.sh # Start the application
      runas: root
      timeout: 300
